In [1]:
import numpy as np
import scipy as sp
import scipy.linalg

## Basis: |0> and |1>

In [2]:
Zero = np.array([[1.0], [0.0]]) # |0>
One = np.array([[0.0], [1.0]]) # |1>

## Function to get Qbit 

In [3]:
NormalizeState = lambda state: state / sp.linalg.norm(state)
def qbit(a, b):
    return NormalizeState(a*Zero + b*One)

## Function to get N Qbits

In [4]:
def NKron(*args):
  """Calculate a Kronecker product over a variable number of inputs"""
  result = np.array([[1.0]])
  for op in args:
    result = np.kron(result, op)
  return result

## Repetition code function

In [5]:
a = 0.1
b = 0.5
qbit(a, b)

array([[0.19611614],
       [0.98058068]])

In [6]:
ZeroZeroZero = NKron(Zero, Zero, Zero) # |000>
OneOneOne = NKron(One, One, One) # |111>
encodedQbit = NormalizeState(a*ZeroZeroZero + b*OneOneOne)
encodedQbit

array([[0.19611614],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.98058068]])

In [7]:
# Id = np.eye(2)

# Z = np.array([[1.0, 0.0],[0.0, -1.0]])
# FlipOne = NKron(Z, Id, Id)
# np.dot(FlipOne, encodedQbit)

## Flip any bit

In [8]:
X = np.array([[0.0, 0.1],[0.1, 0.0]])

In [9]:
Id = np.eye(2)
FlipNone = NKron(Id, Id, Id)
FlipOne = NKron(X, Id, Id)
FlipTwo = NKron(Id, X, Id)
FlipThree = NKron(Id, Id, X)

In [10]:
receivedQbit = np.dot(FlipThree, encodedQbit)
receivedQbit = NormalizeState(receivedQbit)
receivedQbit

array([[0.        ],
       [0.19611614],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.98058068],
       [0.        ]])

## Error Syndrome Check

In [11]:
P0 = np.outer(NKron(Zero, Zero, Zero), NKron(Zero, Zero, Zero)) + np.outer(NKron(One, One, One), NKron(One, One, One))
P1 = np.outer(NKron(One, Zero, Zero), NKron(One, Zero, Zero)) + np.outer(NKron(Zero, One, One), NKron(Zero, One, One))
P2 = np.outer(NKron(Zero, One, Zero), NKron(Zero, One, Zero)) + np.outer(NKron(One, Zero, One), NKron(One, Zero, One))
P3 = np.outer(NKron(Zero, Zero, One), NKron(Zero, Zero, One)) + np.outer(NKron(One, One, Zero), NKron(One, One, Zero))

In [12]:
print(np.dot(receivedQbit.transpose(), np.dot(P0,receivedQbit)))
print(np.dot(receivedQbit.transpose(), np.dot(P1,receivedQbit)))
print(np.dot(receivedQbit.transpose(), np.dot(P2,receivedQbit)))
print(np.dot(receivedQbit.transpose(), np.dot(P3,receivedQbit)))

[[0.]]
[[0.]]
[[0.]]
[[1.]]


## Error Recovery