In [1]:
import numpy as np
import scipy as sp
import scipy.linalg

## |0> and |1>

In [2]:
Zero = np.array([[1.0], [0.0]]) # |0>
One = np.array([[0.0], [1.0]]) # |1>
Zero

array([[1.],
       [0.]])

## |+> or (|0> + |1>)/sqrt(2)

In [3]:
NormalizeState = lambda state: state / sp.linalg.norm(state)
Plus = NormalizeState(Zero + One) # |+> or (|0> + |1>)/sqrt(2)
Plus

array([[0.70710678],
       [0.70710678]])

## |00>

In [4]:
ZeroZero = np.kron(Zero, Zero) # |00>
ZeroZero

array([[1.],
       [0.],
       [0.],
       [0.]])

## |101>

In [5]:
def NKron(*args):
  """Calculate a Kronecker product over a variable number of inputs"""
  result = np.array([[1.0]])
  for op in args:
    result = np.kron(result, op)
  return result

In [6]:
ThreeQubitState = NKron(One, Zero, One) # |101>
ThreeQubitState

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]])

## Operations on multi qubit: H * I * I

In [7]:
Id = np.eye(2)
Hadamard = 1./np.sqrt(2) * np.array([[1, 1],
                                     [1, -1]])
HadamardZeroOnThree = NKron(Hadamard, Id, Id)
HadamardZeroOnThree

array([[ 0.70710678,  0.        ,  0.        ,  0.        ,  0.70710678,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.        ,  0.        ,
         0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.        ,  0.        ,
         0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.70710678,  0.        ,
         0.        ,  0.        ,  0.70710678],
       [ 0.70710678,  0.        ,  0.        ,  0.        , -0.70710678,
        -0.        , -0.        , -0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.        , -0.        ,
        -0.70710678, -0.        , -0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.        , -0.        ,
        -0.        , -0.70710678, -0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.70710678, -0.        ,
        -0.        , -0.        , -0.70710678]])

## H * I * I * |101>

In [8]:
NewState = np.dot(HadamardZeroOnThree, ThreeQubitState)
NewState

array([[ 0.        ],
       [ 0.70710678],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [-0.70710678],
       [ 0.        ],
       [ 0.        ]])